# Generated by Django 3.2.3 on 2021-07-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
