# Generated by Django 3.2.3 on 2021-07-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_acl_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.keystore'),
        ),
    ]
